### ISSUE TITLE
F1TENTH Race Monitor Node

### ISSUE THREAD

**Issue by Mohammed-Azab** [GIU-F1Tenth/race_monitor#1]
Develop a comprehensive ROS2 race monitoring system for F1TENTH autonomous racing with dynamic start/finish line management, real-time lap tracking, and professional visualization.

Requirements Implemented 
Core Functionality

- Dynamic Start/Finish Line: Interactive line setting via RViz "Publish Point" tool
- Accurate Lap Detection: Line segment intersection with heading verification and debounce protection
- Real-time Race Statistics: Live lap counting, timing, and performance metrics
- CSV Data Export: Automatic race results export with detailed statistics
- Professional Visualization: Clean green semi-transparent line with endpoint markers

ROS2 Integration
Subscriptions:

- /odom (nav_msgs/Odometry) → Vehicle position & heading tracking
- /clicked_point (geometry_msgs/PointStamped) → RViz point selection

Publications:

- /race_monitor/lap_count (std_msgs/Int32) → Current lap count
- /race_monitor/lap_time (std_msgs/Float32) → Last lap time
- /race_monitor/best_lap_time (std_msgs/Float32) → Best lap time
- /race_monitor/race_running (std_msgs/Bool) → Race status
- /race_monitor/start_line_marker (visualization_msgs/Marker) → Line visualization

Configuration & Parameters
Configurable Parameters:

- start_line_p1/p2: Default vertical line coordinates [0,-1] to [0,1]
-  required_laps: Race completion threshold (default: 5)
-  debounce_time: False positive prevention (default: 2.0s)
-  output_file: CSV filename customization
-  frame_id: Coordinate frame (default: 'map')

Technical Implementation
Algorithms

- Line Intersection Detection: Counter-clockwise (CCW) algorithm for robust crossing detection
- Heading Verification: Dot product validation ensuring correct crossing direction
- Debounce Logic: Time-based filtering to prevent oscillation false positives
- Visualization Evolution
- Initial: Checkered black/white squares pattern
- Intermediate: Simplified colored line approach
- Final: Professional green semi-transparent line (60% opacity) with endpoint spheres

Data Management
CSV Export Format:
```
lap_number,lap_time_s
1,45.2340
2,43.1250
total_time_s,132.9260
best_lap,43.1250
worst_lap,45.2340
average_lap,44.3087
Package Structure
```
```
race_monitor/
                   ├── package.xml              # ROS2 dependencies & metadata
                   ├── setup.py                 # Python package configuration
                   ├── setup.cfg                # Installation settings
                   ├── README.md                # Comprehensive documentation
                   ├── race_monitor/
                   │   ├── __init__.py          # Package initialization
                   │   └── race_monitor.py      # Main node implementation
                   ├── launch/
                   │   ├── race_monitor_launch.py      # Primary launch file
```

Key Features Delivered

- User Experience
- Intuitive Setup: Click two points in RViz to define start/finish line
- Real-time Feedback: Live lap counting and timing updates
- Visual Confirmation: Clear green line showing detection zone
- Automatic Data Export: Race results saved without manual intervention

**Comment by Mohammed-Azab** [comment]
<img width="734" height="555" alt="Image" src="https://github.com/user-attachments/assets/c5f9dea2-dfbd-432a-a338-e48c6525d3f8" />

**Comment by Mohammed-Azab** [comment]
I forgot that i was on the main branch and then i pushed it directly.
There is an issue in pitlane-util about the lap_timer. The race monitor is more general and contains lap timer inside it. 
As i mentioned in the lap_timer ticket that a submodule of the race_monitor is enough to close that ticket.

**Comment by FamALouiz** [comment]
I believe you forgot to push your code. The main branch is still empty. Unless, you meant to put this in the todo

**Comment by FamALouiz** [comment]
Added at the end of the sprint due to us finishing tasks early
